import { createHash } from "node:crypto";
import type { InferenceConfig } from "../config.js";

export interface GeneratedPlatformArtifacts {
  manifest: {
    version: 1;
    generatedAt: string;
    registryHash: string;
    routesHash: string;
    litellmHash: string;
  };
  litellmConfig: string;
  routes: Array<{
    model: string;
    provider: string;
    protocol: string;
    requestProfile: string;
    enabled: boolean;
  }>;
}

export function generatePlatformArtifacts(config: InferenceConfig, registryHash: string): GeneratedPlatformArtifacts {
  const routes = config.models.map((model) => {
    const provider = config.providers.find((entry) => entry.id === model.providerId)!;
    return {
      model: model.id,
      provider: provider.id,
      protocol: provider.protocol ?? "responses",
      requestProfile: provider.requestProfile ?? "generic-openai",
      enabled: provider.enabled !== false
    };
  });
  const modelList = config.models
    .map((model) => {
      const provider = config.providers.find((entry) => entry.id === model.providerId)!;
      if ((provider.protocol ?? "responses") === "responses") return null;
      const credential = provider.credentialRef ? environmentName(provider.credentialRef) : null;
      const prefix = provider.protocol === "anthropic-messages" ? "anthropic" : "openai";
      return [
        `  - model_name: ${yaml(model.id)}`,
        "    litellm_params:",
        `      model: ${yaml(`${prefix}/${model.upstreamModel}`)}`,
        `      api_base: ${yaml(provider.baseUrl)}`,
        ...(credential ? [`      api_key: ${yaml(`os.environ/${credential}`)}`] : [])
      ].join("\n");
    })
    .filter((entry): entry is string => Boolean(entry))
    .join("\n");
  const masterKey = config.translation ? `os.environ/${environmentName(config.translation.capabilityRef)}` : "disabled-without-translation-config";
  const litellmConfig = [
    "# Generated by codex-router. Automatic routing, retry, fallback, cache, and persistence are intentionally disabled.",
    "model_list:",
    modelList || "  []",
    "general_settings:",
    `  master_key: ${yaml(masterKey)}`,
    "  disable_spend_logs: true",
    "router_settings:",
    "  num_retries: 0",
    "  allowed_fails: 0",
    "  cooldown_time: 0",
    "litellm_settings:",
    "  cache: false",
    "  drop_params: false",
    "  set_verbose: false",
    ""
  ].join("\n");
  const routesHash = hash(routes);
  const litellmHash = hash(litellmConfig);
  return {
    manifest: { version: 1, generatedAt: new Date().toISOString(), registryHash, routesHash, litellmHash },
    litellmConfig,
    routes
  };
}

function environmentName(reference: string): string {
  if (!reference.startsWith("env:")) throw new Error("Generated artifacts accept environment references only");
  return reference.slice(4);
}

function yaml(value: string): string {
  return JSON.stringify(value);
}

function hash(value: unknown): string {
  return createHash("sha256").update(typeof value === "string" ? value : JSON.stringify(value)).digest("hex");
}
